### ISSUE TITLE
auto upload combined2.mp4 file to own youtube channel with translated title & caption

### ISSUE THREAD

**Issue by bugbounted** [Jiaqi07/youtubeAutoDub_0.1#1]
Hi [Jiaqi07](https://github.com/Jiaqi07),
please make changes to auto upload combined2.mp4 file to own youtube channel with translated title & caption.
waiting for your response
finest regards

**Comment by Jiaqi07** [comment]
Hello elmirarokni, that is a separate task that will require knowledge of the Youtube Data API and the google cloud console.  
I will unfortunately not be implementing an auto uploading feature as my auto-translate is very flawed in translating anything relatively complex but I would recommend checking out the video link below and my other repository where I attempted to spam shorts where you can find the code for uploading to youtube. Hope this helps you out!
https://www.google.com/search?q=uploading+youtube+videos+python&rlz=1C1CHBF_enUS940US940&oq=uploading+youtube+videos+python&aqs=chrome..69i57j0i22i30l2j0i390l4.5675j1j4&sourceid=chrome&ie=UTF-8#kpvalbx=_yuG4YvaIO4nXkPIP-pms-Ac45
